### PR TITLE
remove dependency cycle

### PR DESCRIPTION
**Pull request by garlicnation**

### CODE REVIEW

**Comment by 75lb** [comment]
hi! This is all good and i'll merge but out of curiosity, was the cyclic dependency giving you issues? This is the first i've heard of it being an issue..

**Comment by 75lb** [comment]
if it's just a "best practise" suggestion then cool, because it is best practise..

**Comment by garlicnation** [comment]
I'm working on importing these modules into a [bazel](http://bazel.io/)-based build system that doesn't support cycles.

FWIW: I'd love to transfer ownership of object-get to you. I only forked+published to unblock myself.

**Comment by 75lb** [comment]
i see, no problem.. well i'd been gradually splitting array-tools and object-tools up anyway, so all is good.. anyway, these modules are rather "ES5" and outdated so i'm anticipating a slow death.. i don't use them much since native es6 in V8/node.. 

feel free to transfer object-get to 75lb.. i don't think you can transfer npm module ownership though, so just add 75lb as a contributor..  :+1:

**Comment by garlicnation** [comment]
@75lb Repo transfer requested. I published a new version with updated URLs to npm and added you as a contributor.

**Comment by 75lb** [comment]
great thanks.. everything is done, now (i released new versions of array-tools and object-tools which use object-get).. cyclic dependency squashed!

**Pull request merged**
